### ISSUE TITLE
학교 공지사항 조회 API 수정 요청

### ISSUE THREAD

**Issue by sanghyuk-2i** [1sTeam/all-knu-backend#30]
**To Reproduce**

학교 및 학과 공지사항 조회 API를 연동하는 도중 '학교 공지사항 API'에 대한 경로가 Request Parameter을 무시하며 호출하는 경우가 있어,
Path(crawling/notice/univ/{page}) 중 '{page}'를 삭제하고 request으로 받을 수 있는 방법으로 수정 요청

**Error reponse**

<img width="1552" alt="스크린샷 2022-03-16 오전 11 09 15" src="https://user-images.githubusercontent.com/26353827/158502719-a47ff5f9-fe9c-4058-af24-5315ccf5360a.png">
_[사진 1]{page}='1', parameter=3을 호출하면 page=1로 나오는 경우_

<img width="1552" alt="스크린샷 2022-03-16 오전 10 58 24" src="https://user-images.githubusercontent.com/26353827/158502475-f3d925bb-5e7c-4c70-96e7-a9a5f89b8822.png">
_[사진 2]{page}없이 parameter으로만 호출하는 경우_

**Additional context**

**현재 코드 상황**(@PathVariable 수정)
```
@GetMapping("/crawling/notice/univ/{page}") // 학교 공지사항 크롤링 요청
    public ResponseEntity<CommonResponse> getUnivNotice(@PathVariable int page, @RequestParam(value = "type", required = false, defaultValue = "ALL") UnivNoticeType type) {
        List<ResponseCrawling.UnivNotice> notices = crawlingService.getUnivNotice(page, type).orElseGet(() -> null);

        CommonResponse response = CommonResponse.builder()
                .status(HttpStatus.OK.value())
                .message("성공")
                .list(notices)
                .build();
        return new ResponseEntity<>(response, HttpStatus.OK);
    }
```

**Comment by suhongkim98** [comment]
처음엔 전체 공지사항에 페이지만 조회 가능하다가 나중에 학사, 장학 등 타입 조회가 추가되면서 문서화가 덜 되어 생긴 문제인듯..!
일단 페이지 없이 전체 공지사항을 조회하는건 공지사항 게시글을 실시간으로 크롤링 해오는 것이라 불가능해서 무조건 페이지를 지정해서 호출을 해주어야 함 (강남대 공지사항 밑에 페이지 참고)

**API 호출 경로를 수정하겠음**
**GET** `/crawling/notice/univ/{page}?type=[ALL, SCHOLARSHIP...] `
--> **GET** `/crawling/notice/univ/{type}/{page}`
### type
ALL("전체", 0),
  ACADEMIC("학사", 116),
    SCHOLARSHIP("장학", 117),
    LEARNING("학습/상담", 118),
    EMPLOY("취창업", 344); 


### API 호출 예시 
전체 공지사항 1페이지 조회: **GET** `/crawling/notice/univ/ALL/1`
장학 공지사항 1페이지 조회: **GET** `/crawling/notice/SCHOLARSHIP/1`


### 공지사항 인피니티 스크롤 구현 시
공지사항 infinite scroll 구현 시 맨 밑에 도달하면 다음 페이지에 해당하는 값을 page에 넣어 API를 호출해 이어 붙여 보여주는 형태로 구현해야 함

**Comment by suhongkim98** [comment]
서버 띄워서 API 호출 가능합
